version: "3.7"
services:
    webserver:
        container_name: env_setup_webserver
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ../data/web_apps:/var/www/html
            - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: on-failure
        depends_on:
            - php
    php:
        container_name: env_setup_php
        image: php:7.2-fpm
        volumes:
            - ../data/web_apps:/var/www/html
        restart: on-failure
    mysql:
        container_name: env_setup_mysql
        image: mysql:5.7.30
        volumes:
            - ../data/db/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        restart: on-failure
        ports:
            - 3306:3306


